---
title: "JASM 2022"
author: "Alain Danet"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  bookdown::pdf_document2:
    code_folding: hide 
---

- Hi virtual attendance! I am Alain Danet, currently in post-doc at Illinois
  State University. I will talk to you about the drivers and the typology of
  biodiversity trends at global scale.

- Scientists have reached a consensus on the fact that biodiversity is going
  through an unprecedented crisis. Forecast indicates that if we do not act
  strongly and quickly, this crisis will have dramatic consequences that have
  not been seen yet.

- This is particularly true for freshwater ecosystems. Although freshwater
  constitute 0.01% of water on earth, they host almost 9.5% of Earth described
  species. Freshwater biodiversity is mainly threatened by terrestrial land
  degradation, overexploitation, pollution, flow alteration and species
  alteration.

- However we know little on temporal dynamics of freshwater fishes are affected
  by those anthropogenic pressures.

- When an ecologist sampled a community in time, he faces a difficult task.
  Indeed, how to describe the trends in biodiversity of this community?

- Is it the number of species, the total abundance, the dissimilarity of the
  community composition through time? Should I take in account the abundance of
  the species, in other word, compute Hill numbers ?

- Of course, this is no one good answer. But measuring biodiversity in different
  ways, when possible, can help us to refine our understanding biodiversity
  changes. An alternative hypothesis is that biodiversity trends are similar
  among them, and that we might need only a few.

- Regarding the previous research gap, we asked "How do anthropogenic pressures
  influence the temporal trends of freshwater fish biodiversity?" and "Do
  different biodiversity facets have the same temporal trends?"

- To answer those questions, we used the RivFishTime database which contains
  time series of fish communities spanning at least 10 years. The dataset covers
  mostly the so called "Western countries": the US and Canada, Western and North
  Europe, Australia and Japan. For each site, we selected samplings that were
  identical in terms of protocol, measurement unit and sampling season. After
  selection, we had more than 5000 sites.

- We characterised biodiversity by temporal dissimilarity of community
  composition: based on abundance (with Simpson), presence/absence with the
  Jaccard index. We also decomposed Jaccard in Appearance/Disappearance and
  Nestedness/Turnover We also described the Coverage based species richness (the
  Chao) and Total abundance. We also described the composition of communities in
  terms of exotic species.

- We described anthropogenic pressures using the Human Footprint index. It is a
  composite index that take in account human infrastructures, land-use, and
  various characteristics of human occupation. 

- We modelled the temporal trends of biodiversity using hierarchical linear
  models evaluated with INLA, a bayesian framework that approximates posterior
  distribution and thus do not rely on MCMC.

- The biodiversity at a site i and time t is linearly dependent on time,
  covariates and on the interaction among the covariates and time.

- We added random effects on the intercept, alpha and on the temporal trends
  quantified by the slope beta 0. The variance of the intercept and the temporal
  trends were dependent on the hydrographic basin and on the site, nested within
  the basin effect. 

- Today, I will show you only the effect of time (the temporal trends) and its
  interaction with the legacy of long term pressure, the Human footprint of the
  year 1993 and the recent change in pressure quantified by the ratio between
  the human footprint of 2009 and the one of 1993.

- Now, How do anthropogenic pressures influence the temporal trends of
  freshwater fish biodiversity?

- First the results temporal dissimilarity. At the x axis, I displayed the
  standardized slope coefficients. At the Y axis, I displayed the effect of
  time, the temporal trends and how the temporal trends is affected by the
  Legacy of anthropogenic pressures, the recent changes in pressure and their
  interaction. 

- Our results showed both the legacy and recent changes in anthropogenic
  pressures accelerates changes in species composition. 

- Now, the same question with the total abundance, species richness and the
  percentage of exotic species in the communities. 

- We found a global positive temporal trends, confirming previous results on
  aquatic insects. We also see that legacy of past pressure increase the
  temporal trends of total abundance and species richness. Recent increase in
  anthropogenic pressure decrease temporal trends of abundance and richness but
  increase the one of percentage of exotic species.

- Now, Do different biodiversity facets have the same temporal trends?

- The PCA over the temporal trends of biodiversity facets displayed a first axis
  related to dissimilarity of species, a second related to species richness and
  the fourth axis to the temporal trends of Total abundance. 

- The results of the study showed that:
  - Past and recent anthropogenic pressures affect and interact to drive
    biodiversity trends in fish freshwater communities.

- But also that there are several dimensions of temporal trends of biodiversity
  So it might be necessary to assess them simultaneously.

- I want to warmly thank my post doc supervisors for the great collaboration so
  far: namely Lise Comte, my main supervisor, Xingli Giam and Julian Olen,
  co-supersupervisors.

- I would like also to put forward the tremendous work of all the researchers
  and agencies over the world who monitored fish abundance through time and
  provided their data for this project.

- I would also like to especially highlight the herculean work of Lise Comte in
  assembling the RivFishTime database!

- And finally, thank to you for listening! 
