---
title: "Untitled Draft"
author: "Report Author"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  bookdown::html_document2:
    code_folding: hide
---

```{r setup, include=FALSE}
source(here::here("start_rmd.R"))
```

```{r load-targets, include=FALSE}
tar_load(c(filtered_dataset, analysis_dataset))
tar_load(c(rigal_trends, var_temporal_trends))
```

```{r}
test <- analysis_dataset %>%
  select(all_of(c("siteid", "year", var_temporal_trends))) %>%
  nest_by(siteid) %>%
  mutate(data = list(mutate(data, lag1 = lag(species_nb))))


test$data[[1]] %>%
  arrange(year) %>%
  mutate(lag1 = lag(species_nb))
  arima( ~ year + , .)
ti <- c(1,2,3)
lag(ti)
```


```{r}
simple_lm <- map(var_temporal_trends,
  ~analysis_dataset %>%
    nest_by(siteid) %>%
    mutate(
      model = list(lm(as.formula(paste0(.x, " ~ year ")), data = data)),
      res_mod = list(broom::glance(model)),
      coef_mod = list(broom::tidy(model))
    )
)
names(simple_lm) <- var_temporal_trends

```
```{r}
slope <- map_dfr(simple_lm, ~.x %>%
  select(siteid, coef_mod) %>%
  unnest(cols = c(coef_mod)) %>%
  filter(term == "year") %>%
  ungroup(), .id = "response"
)
```


```{r}
slope_df <- slope %>%
  select(siteid, response, estimate) %>%
  pivot_wider(names_from = "response", values_from = "estimate")
```
```{r}
cor_slope <- slope_df %>%
  select(-siteid) %>%
  cor(.)
cor_slope
corrplot::corrplot(cor_slope, type = "lower", tl.srt = 30)
```

```{r}
ti <- expand.grid(
  resp1 = unique(slope$response),
  resp2 = unique(slope$response)
  ) %>%
  filter(resp2 != resp1) %>%
  mutate_all(as.character) %>%
  arrange(resp1)

test <- map2(ti$resp1, ti$resp2,
  function(x, y) {
    bi <- slope %>%
      filter(response %in% c(x, y)) %>%
      select(siteid, response, estimate) %>%
      pivot_wider(names_from = "response", values_from = "estimate")

    return(bi)
  }
)

p <- map(test, function(x) {
  l <- colnames(x)
  x %>%
    ggplot(aes(y = !!sym(l[2]), x = !!sym(l[3]))) +
    geom_point() +
    geom_smooth(method = "lm") +
    labs(y = l[2], x = l[3])
})
p
plot_grid(plotlist = p)
```

- Trends of total abundance are linked to the one of species richness but not to
  shannon and simpson, suggesting that the trends of abundance are more link to
  trends of rare species

```{r}
names(rigal_trends) <- var_temporal_trends 

p <- map2(rigal_trends, names(rigal_trends),
  ~.x %>%
    ggplot(aes(x = first_order_coefficient)) +
    geom_histogram() +
    labs(title = .y)
)
plot_grid(plotlist = p)
```

# Comparison rigal, lm

```{r}
rigal_trends_df <-  map2_dfr(
  rigal_trends, names(rigal_trends),
  ~.x %>% mutate(variable = .y)
  ) %>%
  select(variable, siteid, linear_slope) %>%
  pivot_wider(names_from = "variable", values_from = "linear_slope") %>%
  mutate(type = "rigal")

trends_comp <- rbind(rigal_trends_df, slope_df %>% mutate(type = "simple_lm")) 

```

```{r}
old_par <- par()
par(mfrow = c(3, 2))
for (i in var_temporal_trends) {
  plot(
    trends_comp[trends_comp$type == "rigal", ][[i]] ~
      trends_comp[trends_comp$type == "simple_lm", ][[i]],
    ylab = "Rigal (polynomial degree 2)",
    xlab = "Simple LM"
  )
  abline(0, 1)
  title(i)
}
par(old_par)
```



# Polynomial 

```{r}
get_var_replacement <- function() {
  c(
  log_species_nb = "Log species richness",
  species_nb = "Species richness",
  log_total_abundance = "Log total abundance",
  total_abundance = "Total abundance"
  )
}
```

- Classification:

```{r}
classification_station <- map2(rigal_trends, names(rigal_trends),
  ~.x %>%
  ggplot(aes(x = shape_class)) +
  geom_bar() +
  labs(x = "Trajectory classification", y = "Number of station",
    title = get_var_replacement()[.y])
)

plot_grid(plotlist = classification_station)
```

- Liear trends:

```{r}
#3.3   Log-linear model:logYi=α+βXi+εiIn 

#the log-linear model, the literal interpretation of the estimated
#coefficientˆβis that a one-unitincrease inXwill produce an expected increase in
#logYofˆβunits. 
#In terms ofYitself, this
#meansthat  the  expected  value  ofYis  multiplied  byeˆβ.   So  in  terms  of
#effects  of  changes  inXonY(unlogged):•Each 1-unit increase inXmultiplies the
#expected value ofYbyeˆβ.•To compute the effects onYof another change inXthan an
#increase of one unit, call thischangec, we need to includecin the exponent.  The
#effect of ac-unit increase inXis tomultiply the expected value ofYbyecˆβ. So the
#effect for a 5-unit increase inXwould bee5ˆβ.•For small values ofˆβ,
#approximatelyeˆβ≈1+ˆβ. We can use this for the following approxima-tion for a
#quick interpretation of the coefficients:  100·ˆβis the expected percentage
#changeinYfor a unit increase inX.  For instance forˆβ=.06,e.06≈1.06, so a 1-unit
#change inXcorresponds to (approximately) an expected increase inYof 6%
```


```{r}
#https://data.library.virginia.edu/interpreting-log-transformations-in-a-linear-model/
hist_linear_plot <- map2(rigal_trends, names(rigal_trends),
  ~.x %>%
  ggplot(aes(x = (exp(linear_slope) - 1) * 100)) +
  geom_histogram() +
  labs(x = "Linear slope (% change per year)", y = "Number of station",
    title = get_var_replacement()[.y]) +
  ylim(c(0, 3000))
)
plot_grid(plotlist = hist_linear_plot)
```

# Turnover

```{r, eval=FALSE}
tar_load(hillebrand)
```



## Analysis

## Reproducibility

<details><summary>Reproducibility receipt</summary>

```{r}
## datetime
Sys.time()

## repository
if(requireNamespace('git2r', quietly = TRUE)) {
  git2r::repository()
} else {
  c(
    system2("git", args = c("log", "--name-status", "-1"), stdout = TRUE),
    system2("git", args = c("remote", "-v"), stdout = TRUE)
  )
}

## session info
sessionInfo()
```

</details>
