---
author:
- On behalf of all the authors, Dr. Alain Danet
opening: Dear Chief editor Patrick Goymer, dear Senior Editors,
closing: Sincerely yours,
date: "`r format(Sys.time(), '%d %B, %Y')`"
fontsize: 11pt
return-address:
- Dr. Alain Danet
- School of Biological Sciences
- Illinois State University
- Campus Box 4120 Normal, IL 61790
output:
  linl::linl:
    keep_tex: true

letterhead: misc/letterhead.pdf 
signature: /home/alain/Documents/Administration/signature.pdf
---

```{r, results = "hide", include = FALSE}
Sys.setlocale("LC_TIME", "C")
```


Please find enclosed our manuscript entitled "Past and recent anthropogenic
pressures drive community changes over space and time in riverine fish
communities", which we submit for publication in *Nature in Ecology &
Evolution*.

Documenting community changes is central to ecology, as it is on this basis that
accurate assessment can be done and adequate decisions can be taken. While there
is a scientific consensus on the decline of global biodiversity, community local
biodiversity trends are less clear. This is particularly true in freshwater
systems, which are considered among the most threatened in the world, but for
which recent studies reported increases in the number of individuals and
species occupancy, thus suggesting recovery trajectories from past anthropogenic
pressures. This apparent disagreement between biodiversity changes at global and
local scale calls for investigations addressing both the drivers and the
multidimensionality of community responses, over space and time.

We addressed those research gaps by investigating the effects of both past and
recent changes in anthropogenic pressures over space and time in riverine fish
communities across the globe. Using a compilation of more than 4,000 fish
community timeseries located in several biogeographic realms (i.e., Paleartic,
Neartic and Australasian) and repeatedly sampled over the last decades, we
quantitied changes in species richness and total abundance,
changes in species composition related to species replacement and to dominant
species, and the proportion of non-native species. We related community changes
to past human pressures and its recents changes, as well as the position along
the stream gradients.

We found a global increase in fish species richness and total abundance over
time and that those increases are driven by the legacy of past anthropogenic
pressures, confirming previous findings. But we show that high degree of
historical anthropogenic pressures also result in strong changes in species
identity and changes in dominant species, but also in a increasing share of
non-native species. Our results are coherent with previous findings of ongoing
biotic homogenization of riverine fish communities at larger scale, with and a
key role of non-native species. All together, our results suggest that those
increases in species richness and total abundance are more related to ongoing
recomposition of community to degraded ecosystems rather than a recovery hold by
improvement of water quality as suggested in previous studies. Our results also
highlight that anthropogenic pressures have antagonistic effects on local
diversity, where recent degradations result in decline in species richness and
total abundance while human-driven species introduction result in increase in
species richness and total abundance. We suggest that the complex interacting
effects among past and recent anthropogenic pressures and position along the
stream gradient, might explain our reported complex community trajectories and
their spatial heterogeneity. Our study thus provides a large-scale picture of
the biodiversity trends in an important freshwater group, but also an improved
understanding of the drivers underlying community reassembly in an era of
environmental changes.

As Nature in Ecology & Evolution has been at the forefront of the research on
large-scale biodiversity trends, we are confident that our study will interest
the broad readership of the journal and will stimulate interesting new
perspectives and research on local biodiversity changes at large scale.

The enclosed manuscript has been edited and approved by all the authors and has
not been published or submitted to any other journal. We had no prior
discussions with a Nature Ecology & Evolution editor about the work described in
the manuscript.

As we selected the double-blind peer-review process, we enlist below the ordered list
of authors with their respective affiliation:

- Alain Danet: School of Biological Sciences, Illinois State University, Normal,
    Illinois, USA
- Xingli Giam: Department of Ecology and Evolutionary Biology, The University of
  Tennessee, Knoxville, Tennessee, USA
- Julian Olden: School of Aquatic and Fishery Sciences, University of
  Washington, Seattle, Washington, USA
- Lise Comte: School of Biological Sciences, Illinois State University, Normal,
  Illinois, USA

We propose potential reviewers for their respective expertise regarding our
study:

- Charlotte Outhwaite, Centre for Biodiversity and Environment Research,
  University College London, London, UK:
  - expertise: Effects of human pressures on biodiversity trends 
  - `charlotte.outhwaite.14@ucl.ac.uk`
- Mark Vellend, Département de biologie, Université de Sherbrooke, Sherbrooke, QC, Canada: 
  - expertise: biodiversity trends at local and regional scale 
  - `mark.vellend@usherbrooke.ca`
- Sébastien Villéger: MARBEC, Univ Montpellier, CNRS, Ifremer, IRD, Montpellier, France: 
  - expertise: Biotic homogeneization and non-native species introduction in riverine fish communities
  - `sebastien.villeger@cnrs.fr`
    
