---
title: "Supplementary Figures and Tables"
author: "Danet, A, Giam, X, Olden, J, Comte, L"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  bookdown::pdf_document2:
    keep_tex: true
    df_print: paged
    toc: true
bibliography: "bibliography.bib"
always_allow_html: true
header-includes:
  \usepackage{float}
  \usepackage{booktabs}
  \usepackage{colortbl}
---

```{r options, include = FALSE}
knitr::opts_chunk$set(echo = FALSE,
  message = FALSE,
  warning = FALSE,
  collapse = TRUE,
  comment = "#>",
  fig.path = "graphics/knitr-",
  fig.retina = 1.618, # Control using dpi
  fig.width = 6,  # generated images
  fig.pos = "t",  # pdf mode
  fig.align = "center",
  dpi = if (knitr::is_latex_output()) 72 else 300,
  out.width = "80%",
  dev = "svg",
  dev.args = list(png = list(type = "cairo-png")),
  optipng = "-o1 -quiet")
options(kableExtra.latex.load_packages = TRUE)
library(kableExtra)
```

```{r library, include = FALSE}
source(here::here("start_rmd.R"))
theme_set(theme_cowplot())
theme_update(axis.text = element_text(size = 8))
library(gt)
library(gtsummary)
library(ggbreak)
```

```{r}
get_tbl_summary <- function(df = NULL) {

t1 <- df %>%
  tbl_summary(statistic = all_continuous() ~ "{N_nonmiss}", missing = "no") %>%
  modify_header(stat_0 ~ "**N (no missing)**")

t2 <- df %>%
  tbl_summary(statistic = all_continuous() ~
    "{median} ({p25}, {p75})",
  missing = "no") %>%
  modify_header(stat_0 ~ "Median (1st Q, 3rd Q)")

t3 <- df %>%
  tbl_summary(statistic = all_continuous() ~
    "({min}, {max})",
  missing = "no") %>%
  modify_header(stat_0 ~ "(Min, Max)")

tbl_merge(list(t1, t2, t3)) %>%
  modify_footnote(everything() ~ NA_character_) %>%
  modify_spanning_header(everything() ~ NA_character_)

}
ecdf_fun <- function(x, perc) ecdf(x)(perc)
```

```{r}
source("https://raw.githubusercontent.com/EmilHvitfeldt/emilfun/master/R/palette_scrapers.R")
pal_variable <- palette_coolors("https://coolors.co/palette/ff0000-ff8700-ffd300-deff0a-a1ff0a-0aff99-0aefff-147df5-580aff-be0aff")

legend_order <- c(
  "hillebrand_dis_scaled", "jaccard_dis_scaled", "turnover_scaled", "nestedness_scaled", "appearance_scaled", "disappearance_scaled",
  "log_total_abundance",
  "log_chao_richness", "perc_exo_abun", "perc_exo_sp")

names(pal_variable) <- get_var_replacement_vulgarisation()[legend_order]

restricted_dimension <- c(
  "hillebrand_dis_scaled", "turnover_scaled", "log_total_abundance",
  "log_chao_richness", "perc_exo_abun", "perc_exo_sp")
```

```{r}
tar_load(c(add_dataset_ref))
tar_load(filtered_op_protocol_modelling)
tar_load(filtered_dataset_modelling)
tar_load(c(modelling_data, modelling_data_exo))
tar_load(c(clust_var, exo_resp_var))
tar_load(riveratlas_site)
tar_load(c(
    site_no_drivers_inla_tot, site_env,
    gaussian_inla_std_effects, gaussian_inla_exo_std_effects)
)

tar_load(c(measurement_exo))
# filter
measurement_exo <- measurement_exo %>%
  filter(op_id %in% unique(modelling_data_exo$op_id))
```

\newpage


```{r}
trends_cap <- "Distribution of temporal trends by decade of community metrics
across sites. Total abundance and species richness are expressed in percentage change by decade."
```

```{r, fig.width = 12, fig.asp = 1, fig.cap=trends_cap}
resp_lvl <- get_var_replacement_vulgarisation()[legend_order]

tps_trends_10y <- site_no_drivers_inla_tot %>%
  pivot_longer(everything(), names_to = "response", values_to = "value") %>%
  mutate(
    response = get_var_replacement_vulgarisation()[response],
    response_f = factor(response, levels = get_var_replacement_vulgarisation()[legend_order]),
    value = ifelse(response %in% c("Total abundance", "Species richness"),
      log_beta_to_perc_rate(value), value),
    response = ifelse(response %in% c("Total abundance", "Species richness"),
      paste0(response, " (%)"), response),
    response_f = fct_recode(response_f,
      "Total abundance (%)" = "Total abundance",
      "Species richness (%)" = "Species richness",
      ), 
    value = value * log(10 + 1)
  )
tps_trends_10y %>%
  ggplot(aes(x = value)) +
  geom_histogram(fill = "lightblue", bins = 60) +
  geom_vline(xintercept = 0, linetype = "dashed", colour = "red") +
  labs(x = "Temporal trends by decade", y = "Number of sites") +
  scale_x_continuous(n.breaks = 10) +
  facet_wrap(vars(response_f), scales = "free",
    ncol = 3, strip.position = "top") +
  theme(strip.background = element_blank())
```
 
```{r}
tu_full <- rbind(gaussian_inla_std_effects,
  gaussian_inla_exo_std_effects) %>%
  filter(!str_detect(term, "unitabundance|Intercept")) %>%
  mutate(
    term = str_replace_all(term, get_model_term_replacement_paper_figure()),
    response = get_var_replacement_vulgarisation()[response]
    )
```

```{r, fig.show = "hide"}

p1_f <- tu_full %>%
  filter(facet == "main") %>%
  arrange(desc(width_bar)) %>%
  plot_inla_fixed_effect(
    term_level = get_term_level(),
    scale_color = rev(pal_variable)
    ) +
  scale_x_break(c(.21, .5))

p2_f <- tu_full %>%
  filter(facet == "interaction") %>%
  arrange(desc(width_bar)) %>%
  plot_inla_fixed_effect(
    term_level = get_term_level(),
    scale_color = rev(pal_variable)
  )

p3_f <- tu_full %>%
  filter(facet == "dbl_interaction") %>%
  arrange(desc(width_bar)) %>%
  plot_inla_fixed_effect(.,
    term_level = get_term_level(),
    scale_color = rev(pal_variable),
    legend_present = TRUE,
    xaxis_title = TRUE
    ) +
  labs(x = expression(
      paste("Standardized slope coefficients ",
        beta, "' (", "s.d. unit)",
        sep = "")
    )
  )


leg_dis <- get_legend(
  p3_f +
    guides(
      colour = guide_legend(nrow = 4)) +
  theme(
    legend.position = "bottom",
    legend.text = element_text(size = 10),
    legend.title = element_blank()
  ) +
scale_color_manual(
  values = pal_variable,
  labels = names(pal_variable)#map(var_labels, ~parse(text = .x))
)
)

figS1 <- plot_grid(
  print(p1_f),
  print(p2_f),
  p3_f + theme(legend.position = "none"),
  leg_dis,
  rel_heights = c(1, 1, 1, .2),
  ncol = 2)
```

```{r}
std_tot_cap <- "**Responses of  community metrics to time, local
  anthropogenic pressures, stream gradient and their interaction**. See Fig. 3
in the main text for details. To the difference with the Fig. 3, we
added Jaccard dissimilarity index and its partitions in two sets of
complementary indices, respectively nestedness/turnover, and
appearance/disappearance."
```


```{r std-tot, fig.width = 10, fig.asp = 1.3, fig.cap=std_tot_cap}
figS1
```

```{r}
tar_load(c(pca_clust, site_cl_rm, site_no_drivers_inla_tot))
tar_load(c(clust_var_alter, site_cl_rm_red, site_env))
pca_data <- site_no_drivers_inla_tot[,
    colnames(site_no_drivers_inla_tot) %in% restricted_dimension &
    !colnames(site_no_drivers_inla_tot) %in% c("perc_exo_sp", "perc_exo_abun")]
pca_clust <- compute_rotated_pca(pca_data, naxis = 4)
```

```{r}
axis_l <- list(
  c("CS1", "CS2"),
  c("CS3", "CS4")#,
#  c("CS5", "CS6"),
#  c("CS7", "CS8")
)

cluster_names <- c(
  "Medium change", "High turnover",
  "Increase in\n species richness", "Decrease in\n total abundance",
  "Decrease in\n species richness", "Low change"
)
fnsite <- nrow(site_cl_na)
nb_clusters <- table_to_vec(table(site_cl_rm$cl))
per_cluster <- scales::percent(nb_clusters / sum(nb_clusters))
na_cluster <- paste0("(N = ",
  fnsite - sum(nb_clusters), ", ", scales::percent((fnsite - sum(nb_clusters)) / fnsite),")"
)

cluster_labels <- map2_chr(cluster_names, paste0(nb_clusters, ", ", per_cluster),
  ~paste0(.x, "\n(N = ", .y, ")"))

p_pca_cl_ell <- map(axis_l,
  ~plot_pca_clust(
     .data = pca_clust$normal,
     site_cl = site_cl_rm,
     add_point = TRUE,
     add_ellipse = TRUE,
     xaxis = .x[1], yaxis = .x[2],
     ctb_thld = .25,
     replace_var = get_var_replacement_vulgarisation(),
     size_arrows_segment = 1,
     label_size = 2.5,
     alpha_point = .2,
     lim_x_y = c(-3.5, 3.5),
     force_pull = 1,
     force = 1,
     var_scaling_factor = 3.5
   ) +
 guides(
   colour = guide_legend(
     override.aes = list(size = 8),
     title.theme = element_blank(),
     label.position = "top",
     ncol = 2)
 ) +
 theme(
   legend.position = "bottom",
   panel.background = element_blank(),
   legend.text = element_text(size = 8),
   legend.key = element_rect(fill = NA)) +
 scale_color_viridis(
   discrete = TRUE,
   name = "Cluster", labels = cluster_labels)
)
leg_cl <- get_legend(
  p_pca_cl_ell[[1]]
)

p_pca_cl_ell <- map(p_pca_cl_ell,
  ~.x + theme(legend.position = "none"))
```

```{r}
pca_total_cap <- "**PCA biplot on the temporal trends of the
  community metrics at each site, and their cluster assignment**. See legend of
the Fig. 1 in main text for details. To the difference with the Fig. 1, we
added Jaccard dissimilarity index and its partitions in two sets of
complementary indices, respectively nestedness/turnover, and
appearance/disappearance." %>%
  str_remove_all("\n|\r") %>%
  str_replace_all("  ", " ")
```

```{r}
bp_data <- site_cl_rm[, colnames(site_cl_rm) %in% c(legend_order[!str_detect(legend_order, "perc")], "siteid", "cl", "riv_str_rc1", "hft_c9309_scaled_no_center")]
p_pca_cl_bt <- target_bp_cl_dist(
  cl_obj = bp_data,
  fct_var_lvl = names(pal_variable)[1:8],
  dodge = .85
  ) +
  scale_color_viridis(discrete = TRUE) +
  scale_fill_viridis(discrete = TRUE) +
  scale_x_discrete(position = "bottom") +
  labs(y = "Scaled temporal trends (SD units)") +
  theme(
    axis.text.x = element_text(angle = 0, vjust = 0),
    axis.title.y = element_text(angle = 90, vjust = 0),
    legend.position = "none"
  )
```


```{r pca-tot, fig.width = 12, fig.asp = .8, fig.cap = pca_total_cap}
p_pca_cl_top <- plot_grid( p_pca_cl_ell[[1]], p_pca_cl_ell[[2]], ncol = 2)
bottom_cl <- plot_grid(p_pca_cl_bt, leg_cl, rel_widths = c(1, .25))
plot_grid(p_pca_cl_top, bottom_cl,
  nrow = 2,
  rel_heights = c(1, 1))
```


```{r}
tar_load(c(pred_gaussian_inla, pred_gaussian_inla_exo, pred_data_explanation))

pred_gaussian_inla_tot <- rbind(
  pred_gaussian_inla %>%
    filter(response %in% clust_var),
  pred_gaussian_inla_exo
  )
# exclude riv
pred_to_keep <- names(pred_gaussian_inla_tot$pred_plot[[1]])[!str_detect(names(pred_gaussian_inla_tot$pred_plot[[1]]), "riv")]
pred_gaussian_inla_tot <-
  pred_gaussian_inla_tot %>%
  mutate(
    pred_plot = map(pred_plot, ~map(.x[pred_to_keep], ~.x +
        theme(legend.position = "bottom")))
  )
```



```{r}
selected_pred <- list(
  "log1_year_nb" = c("0", "10"),
  "riv_str_rc1" = c("median"),
  "hft_ix_c93" = c("intact", "max"),
  "hft_ix_c9309_log2_ratio" = c("div/2", "inc/2")
)
val_pred_selected <- map2(
  pred_data_explanation, names(pred_data_explanation),
  ~(.x[selected_pred[[.y]]])
)

tab_pred <- enframe(val_pred_selected) %>%
  unnest(value) %>%
  mutate(
    signif = unlist(map(names(pred_data_explanation), ~selected_pred[[.x]])),
    Signification = get_pred_signification()[signif],
    driver_name =  get_model_term_replacement_paper_figure()[name],
    name = str_replace(get_model_term_replacement()[name], "\n", " "),
    value = round(value, 1)
  ) %>%
  select(
    Driver = driver_name,
    `Predictor variable` = name,
    Value = value, Signification
  )
```

```{r, eval=FALSE}
tab_pred_cap <- "Values and signification of predictor variables used in the
main text."
tab_pred %>%
  kbl(booktabs = T,
    label = "tab-pred",
    caption = tab_pred_cap) %>%
  column_spec(4, width = "5cm") %>%
  collapse_rows(columns = c(1, 2), latex_hline = "major", valign = "middle") %>%
  kable_styling(latex_options = c("striped", "hold_position"))
```

```{r, fig.asp = 5, fig.width = 12, eval=FALSE}
pred_list <- list()
for (i in seq_len(nrow(pred_gaussian_inla_tot))) {
  pred_list[[i]] <- plot_grid(plotlist = pred_gaussian_inla_tot$pred_plot[[i]], ncol = 3,
    labels = get_var_replacement_vulgarisation()[pred_gaussian_inla_tot$response[i]], label_y = 1)
}
plot_grid(plotlist = pred_list, ncol = 1)
```

\newpage

```{r}
tar_load(c(gaussian_inla_rand, r2))
library(coda)

tu <- r2 %>%
  filter(response %in% c(clust_var, exo_resp_var))
tab_rand <- gaussian_inla_rand %>%
  filter(
    ci_level == "level:0.95",
    response %in% c(restricted_dimension, exo_resp_var)
    ) %>%
  select(-ci_level) %>%
  mutate(across(c(mean, low, high), ~round(., 3))) %>%
  mutate(
    response = get_var_replacement_vulgarisation()[response],
    term = str_remove(term, "Precision for the |Precision for |"),
    term = replacement_random_term()[term],
    ci = paste0(mean, " [", high,",", low,"]")
  ) %>%
  arrange(response, desc(term)) %>%
  select(
    `Response variable` = response,
    `Term` = term,
    `S.D. [CI 95%]` = ci
  )

tab_rand2 <- tab_rand %>%
  left_join(
    tu %>%
      mutate(response = get_var_replacement_vulgarisation()[response]) %>%
      select(
        `Response variable` = response,
        `Marg. R2` = r2_mvp_marg95hpdci,
        `Cond. R2` = r2_mvp_cond95hpdci
        ),
    by = "Response variable"
    ) %>%
  select(1, 4, 5, 2, 3) %>%
  mutate(`Response variable` = factor(`Response variable`, levels = names(pal_variable))) %>%
  arrange(`Response variable`)
```

```{r}
tab_rand_cap <- "Mean marginal and conditional R-squared of the models and the mean standard deviation estimated for the random effects and the error term. [95\\% CI]: Credible Interval computed using Highest Posterior Density method."
tab_rand2 %>%
  kbl(booktabs = T,
    label = "tab-rand",
    caption = tab_rand_cap) %>%
  collapse_rows(columns = c(1, 2, 3), latex_hline = "major", valign = "middle") %>%
  kable_styling(latex_options = c("striped", "hold_position", "scale_down"))
```


```{r}
add_dataset_ref %>%
  select(-Program, -`Database source`) %>%
  kbl(booktabs = T,
    label = "tab-add-data",
    caption = "Databases included in the current study that were not included in
    RivFishTIME publication (Comte et al., 2021a). Apart from MARIS, these
    databases have already been used in a previous study (Comte et al.,
      2021b). N: number of sites.") %>%
  kable_styling(latex_options = c("striped", "hold_position")) %>%
  column_spec(4, width = "10cm")
```

```{r tab-pro-ch, results = "hide"}
tab_protocol <- tabyl_df(filtered_dataset_modelling$site_quali, "protocol") %>%
  mutate(
    method = "Protocol",
    protocol = str_replace_all(protocol, "_", " "),
    # For rotenone:
    protocol = str_replace_all(protocol, "([a-z])([A-Z])", "\\1 \\2")
    ) %>%
  rename_with(str_to_sentence) 

```
```{r, eval=FALSE}
tab_protocol %>%
  kbl(booktabs = T,
    label = "tab-pro",
    caption = "Protocol occurrence across sites"
    ) %>%
  kable_styling(latex_options = c("striped", "hold_position"))
```



```{r tab-u-ch, results = "hide"}
abun_unit <- tabyl_df(filtered_dataset_modelling$site_quali, "unitabundance") %>%
  mutate(
    method = "Abundance unit",
    unitabundance = str_replace_all(unitabundance, "_", " "),
    unitabundance = str_replace_all(unitabundance, get_unitabun_replacement())
    ) %>%
  rename_with(str_to_sentence) %>%
  rename(`Abundance unit` = Unitabundance)
```

```{r, eval=FALSE}
abun_unit %>%
  kbl(booktabs = T,
    label = "tab-u",
    caption = "Abundance unit across sites"
    ) %>%
  kable_styling(latex_options = c("striped", "hold_position"))
```


```{r tab-loc-u, results = "hide"}
location_site <- filtered_dataset_modelling$location %>%
  mutate(ecoregion = str_replace(ecoregion, "Neartic", "Nearctic")) %>%
  group_by(ecoregion, country)

location_summary <- location_site %>%
    summarise(n = n(), .groups = "drop") %>%
    mutate(
      method = "Site location (Country, Realm)",
      country_realm = paste0("(", country,  ", ", ecoregion, ")"),
      percent = scales::percent(n / sum(n), accuracy = .01)
    ) %>%
    arrange(desc(ecoregion), desc(n)) %>%
    rename(realm = ecoregion) %>%
    rename_with(str_to_sentence)
```
```{r, eval=FALSE}
location_summary %>%
  kbl(booktabs = T,
    label = "tab-loc",
    caption = "Realm and country occurrence across sites"
    ) %>%
  kable_styling(latex_options = c("striped", "hold_position"))
```


```{r}
exotic_source_summary <- measurement_exo[, "native_exotic_origin"] %>%
  group_by(native_exotic_origin) %>%
  summarise(n = n(), .groups = "drop") %>%
  mutate(
    method = "Source for native species status",
    percent = scales::percent(n / sum(n), accuracy = .01),
    native_exotic_origin = get_nat_origin_replacement()[native_exotic_origin]
    ) %>%
  arrange(desc(n)) %>%
  rename(`Source for native species status` = native_exotic_origin) %>%
  rename_with(str_to_sentence)
```

```{r met-tab}
method_lvl <- c("Site location (Country, Realm)", "Protocol", "Abundance unit", 
  "Source for native species status")
tab_quali <- rbind(
  location_summary %>%
    select(Method, Value = Country_realm, N, Percent),
  tab_protocol %>%
    select(Method, Value = Protocol, N, Percent),
  abun_unit %>%
    select(Method, Value = `Abundance unit`, N, Percent),
  exotic_source_summary %>%
    select(Method, Value = `Source for native species status`, N, Percent)
  ) %>%
mutate(Method = factor(Method, levels = method_lvl)) %>%
filter(Value != "Total") %>%
arrange(Method, desc(N))
```

```{r, eval=TRUE}
tab_quali %>%
  kbl(booktabs = T,
    label = "tab-met",
    caption = "Site location, protocol and abundance unit occurrences across sites, and data source for native species status in term of species occurrence.") %>%
  collapse_rows(columns = 1, latex_hline = "major", valign = "middle") %>%
  kable_styling(latex_options = c("striped", "hold_position"))
```



```{r tab-exo-source-ck, eval=FALSE}
exotic_source_summary %>%
  kbl(booktabs = T,
    label = "tab-exo-source",
    caption = "Data source for native species status in term of species occurrence.") %>%
  kable_styling(latex_options = c("striped", "hold_position"))
```


```{r}
year_op_cap <- "Distribution of year of samplings. Years 1993 and 2009,
corresponding to the two human footprint measurements, are highlighted."
```

```{r y-op, fig.cap=year_op_cap}
seg <- tibble(
 x = c(1993, 2009),
 y = c(0, 0),
 xend = x,
 yend = c(7500, 6500)
)

nb_op9309 <- sum(
  filtered_op_protocol_modelling$year >= 1993
)
perc_op9309 <- scales::percent(sum(filtered_op_protocol_modelling$year >= 1993)
  / nrow(filtered_op_protocol_modelling))

txt <- tibble(
 x = c(1987, 1993, 2001, 2008, 2009, 2015),
 y = c(7500, 7500, 6000, 7500, 6500, 6000),
 label = c(
   paste0(
   scales::percent(sum(filtered_op_protocol_modelling$year <= 1993)
     / nrow(filtered_op_protocol_modelling)),
   " in [", min(filtered_op_protocol_modelling$year), ",1993]"
   )
   ,
   "1993",

   paste0(
scales::percent(sum(filtered_op_protocol_modelling$year >= 1993 & filtered_op_protocol_modelling$year <= 2009)
  / nrow(filtered_op_protocol_modelling)),
   " in [1993,2009]"
   ),
 paste0(
   scales::percent(sum(filtered_op_protocol_modelling$year >= 1993)
     / nrow(filtered_op_protocol_modelling)),
   " in [1993,", max(filtered_op_protocol_modelling$year), "]"
   ),
 "2009",
 paste0(
scales::percent(sum(filtered_op_protocol_modelling$year >= 2009)
  / nrow(filtered_op_protocol_modelling)),
   " in [2009,", max(filtered_op_protocol_modelling$year), "]"
   )
 )
) %>%
mutate(label = str_replace(label, "in ", "in\n")) %>%
filter(! x %in% c(1993, 2009))

distr_protocol <- filtered_op_protocol_modelling %>%
  ggplot(aes(x = year)) +
  geom_histogram() +
  scale_x_continuous(breaks = c(1960, 1980, 1993, 2000, 2009, 2020)) +
  geom_segment(data = seg,
    aes(x = x, y = y, xend = xend, yend = yend),
    lwd = 1, color = "gray80", linetype = "dashed"
    ) +
  labs(x = "Year", y = "Number of samplings") +
  geom_label(data = txt,
    aes(x = x, y = y, label = label)
  )
```

```{r}
tar_load(site_year)
```

```{r}
seg_bl <- tibble(
 x = c(1993, 2009),
 y = c(0, 0),
 xend = x,
 yend = c(700, 600)
)
txt_bl <- tibble(
 x = c(1987, 1993, 2001, 2008, 2009, 2015),
 y = c(700, 700, 600, 700, 600, 600),
 label = c(
   paste0(
   scales::percent(sum(site_year$min <= 1993)
     / nrow(site_year)),
   " in [", min(site_year$min), ",1993]"
   )
   ,
   "1993",
   paste0(
scales::percent(sum(site_year$min >= 1993 & site_year$min <= 2009)
  / nrow(site_year)),
   " in [1993,2009]"
   ),
 paste0(
   scales::percent(sum(site_year$min >= 1993)
     / nrow(site_year)),
   " in [1993,", max(site_year$min), "]"
   ),
 "2009",
 paste0(
scales::percent(sum(site_year$min >= 2009)
  / nrow(site_year)),
   " in [2009,", max(site_year$min), "]"
   )
 )
) %>%
mutate(label = str_replace(label, "in ", "in\n")) %>%
filter(! x %in% c(1993, 2009))

p_baseline_year <- site_year %>%
  ggplot(aes(x = min)) +
  geom_histogram() +
  scale_x_continuous(breaks = c(1960, 1980, 1993, 2000, 2009, 2020),
  limits = c(1960, 2020) 
    ) +
  labs(x = "Baseline year", y = "Number of sites") +
  geom_segment(data = seg_bl,
    aes(x = x, y = y, xend = xend, yend = yend),
    lwd = 1, color = "gray80", linetype = "dashed"
    ) +
  geom_label(data = txt_bl,
    aes(x = x, y = y, label = label)
  )
```


```{r}
p_span <- site_year %>%
  ggplot(aes(x = cat_span, fill = ecoregion)) +
  geom_bar() +
  labs(x = "Year span (year)", y = "Number of sites") 
#+
#  theme(axis.text.x = element_text(angle = 30, hjust = 1))

p_completness <- site_year %>%
  ggplot(aes(x = cat_completeness, fill = ecoregion)) +
  geom_bar() +
  labs(
    x = "Completeness of sampling (nb sampling / year span )",
    y = "Number of sites"
  )
```

```{r}
cap <- "Distribution of (A) sampling years (B) baseline year, (C) year span and
(D) completeness of sampling by site."
```

```{r base-span-cpl, fig.cap=cap, fig.width = 13, fig.asp = 1}
leg_ecoregion <- get_legend(
  p_span + guides(fill = guide_legend(title = NULL)))
plot_grid(
  plot_grid(distr_protocol, p_baseline_year, ncol = 2, labels = c("A", "B")),
  plot_grid(
    p_span + theme(legend.position = "none"),
    p_completness + theme(legend.position = "none"),
    leg_ecoregion,
    ncol = 3,
    rel_widths = c(1, .8, .3),
    labels = c("C", "D")
    ),
  nrow = 2
)
```
\newpage


```{r tab-resp-ck}
tmp <- modelling_data %>%
  left_join(
    modelling_data_exo %>%
      select(siteid, year, perc_exo_sp, perc_exo_abun),
    by = c("siteid", "year")
  ) %>%
  select(all_of(c("chao_richness", "species_nb",
        clust_var, exo_resp_var)))
resp_summary <- tmp %>%
  pivot_longer(everything(),
    names_to = "Community metric",
    values_to = "values") %>%
  group_by(`Community metric`) %>%
  summarise(summ = list(enframe(summary_distribution(values)))) %>%
  unnest(summ) %>%
  pivot_wider(names_from = "name", values_from = "value") %>%
  mutate(
    median = format(round(median, 2), nsmall = 2),
    `Median (Q1, Q3)` = paste0(median, " (",
      format(round(`1st_quart`, 2), nsmall = 2), ",",
      format(round(`2nd_quart`, 2), nsmall = 2),
      ")"),
    `(Min, Max)` = paste0("(",
      format(round(min, 2), nsmall = 2),
      ",",
      format(round(max, 2), nsmall = 2),
      ")")
  ) %>%
  select(`Community metric`, N = n, `Median (Q1, Q3)`, `(Min, Max)`, median) %>%
  arrange(median) %>%
  select(-median)
```

```{r, tab_exo}
exo_sp_var <- c(
  "species_nb_nat", "species_nb_exo",
   "perc_nat_sp", "perc_nat_abun"
)

tmp <- modelling_data_exo %>%
  select(all_of(exo_sp_var))
exotic_compo_summary <- tmp %>%
  pivot_longer(everything(),
    names_to = "Community metric",
    values_to = "values") %>%
  group_by(`Community metric`) %>%
  summarise(summ = list(enframe(summary_distribution(values)))) %>%
  unnest(summ) %>%
  pivot_wider(names_from = "name", values_from = "value") %>%
  mutate(
    median = format(round(median, 2), nsmall = 2),
    `Median (Q1, Q3)` = paste0(median, " (",
      format(round(`1st_quart`, 2), nsmall = 2), ",",
      format(round(`2nd_quart`, 2), nsmall = 2),
      ")"),
    `(Min, Max)` = paste0("(",
      format(round(min, 2), nsmall = 2),
      ",",
      format(round(max, 2), nsmall = 2),
      ")")
  ) %>%
  select(`Community metric`, N = n, `Median (Q1, Q3)`, `(Min, Max)`) %>%
  arrange(`Community metric`)
```

```{r}
restricted_dimension <- c(
  "hillebrand_dis_scaled", "turnover_scaled", "log_total_abundance",
  "log_chao_richness", "perc_exo_abun", "perc_exo_sp")
response_summary_tot <- rbind(resp_summary, exotic_compo_summary) %>%
  mutate(
    main_text = get_var_replacement_vulgarisation()[`Community metric`],
    main_text = ifelse(`Community metric` %in% restricted_dimension, main_text, ""),
    main_text = factor(main_text, levels = get_var_replacement_vulgarisation()[restricted_dimension]),
    `Community metric` = get_var_replacement()[`Community metric`]
  ) %>%
arrange(main_text, `Community metric`) %>%
select(1, `Main text name` = main_text, N, 3, 4)
```



```{r, eval=FALSE, results = "hide"}
resp_summary %>%
  kbl(booktabs = T,
    label = "tab-resp",
    caption = "Summary descriptors of response variables distribution"
    ) %>%
  kable_styling(latex_options = c("striped", "hold_position"))
```


```{r tab-exo-ck, eval=FALSE}
exotic_compo_summary %>%
  kbl(booktabs = T,
    label = "tab-exo",
    caption = "Summary distribution of native and non-native species metrics") %>%
  kable_styling(latex_options = c("striped", "hold_position"))
```

```{r}
cor_chao_rich <- cor(
  modelling_data$chao_richness,
  modelling_data$species_nb,
  method = "spearman") %>%
round(., 2)
chao_richness_cap <- paste0("Relationship between Chao-corrected species richness and
species richness, added to their respective distribution. The black line
displays the bissection, i.e. the intercept and slope are respectively 0 and 1.
Spearman's correlation is equal to ", cor_chao_rich, ".")
```


```{r chao-nb, fig.cap = chao_richness_cap}
p <- modelling_data %>%
  ggplot(aes(x = species_nb, y = chao_richness)) +
  geom_point(alpha = .3, color = "gray70") +
  geom_abline(intercept = 0, slope = 1) +
  labs(y = "Chao species richness", x = "Species richness")

ggExtra::ggMarginal(p, type = "histogram")
```

```{r}
tar_load(pca_riv_str)
```


```{r}
col_pca_riv <- c(
  "siteid", "dist_up_km", "ord_stra",
  "dis_m3_pyr", "ele_mt_cav", "slp_dg_cav",
   "hft_ix_c93", "hft_ix_c09"
)

riveratlas_tmp <- riveratlas_site %>%
  select(all_of(col_pca_riv)) %>%
  st_drop_geometry() %>%
  left_join(
    modelling_data %>%
      distinct(siteid, hft_ix_c9309_log2_ratio, riv_str_rc1),
    by = "siteid") %>%
  select(-siteid) %>%
  mutate(hft_ix_c93  = hft_ix_c93 / 10,
    hft_ix_c09 = hft_ix_c09 / 10,
    hft_ix_c9309_ratio = hft_ix_c09 / hft_ix_c93)

evt_summary <- riveratlas_tmp %>%
  pivot_longer(everything(),
    names_to = "metrics",
    values_to = "values") %>%
rbind(., modelling_data %>%
  select(year_nb, log1_year_nb) %>%
  pivot_longer(everything(),
    names_to = "metrics",
    values_to = "values")) %>%
  group_by(metrics) %>%
  summarise(summ = list(enframe(summary_distribution(values)))) %>%
  unnest(summ) %>%
  pivot_wider(names_from = "name", values_from = "value") %>%
  mutate(
    name = str_replace_all(metrics,
      c(
        get_rev_vec_name_val(get_river_atlas_significant_var()),
        riv_str_rc1 = "PCA axis 1: stream gradient",
        get_model_term_replacement()
      )
    ),
    median = format(round(median, 2), nsmall = 2),
    `Median (Q1, Q3)` = paste0(median, " (",
      format(round(`1st_quart`, 2), nsmall = 2), ",",
      format(round(`2nd_quart`, 2), nsmall = 2),
      ")"),
    `(Min, Max)` = paste0("(",
      format(round(min, 2), nsmall = 2),
      ",",
      format(round(max, 2), nsmall = 2),
      ")"),
    main_text = get_model_term_replacement_paper_figure()[metrics],
  ) %>%
  select(`Environmental variables` = name, `Main text name` = main_text,
    N = n, `Median (Q1, Q3)`, `(Min, Max)`) %>%
  arrange(`Main text name`, `Environmental variables`)

```
```{r, eval=FALSE}
evt_summary %>%
  kbl(booktabs = T,
    label = "tab-riv",
    caption = "Descriptive statistics for the numerical predictors used for
    modelling. Main text names display the name used in the legend of the
    figures in main text. The community metrics that do not have main text name
    were not used in the analysis reported in main text. The PCA summarising the stream gradient
    was computed with Average annual discharge, Average elevation, Average slope, Distance from source, and Strahler order (Fig. SXX).") %>%
  kable_styling(latex_options = c("striped", "hold_position"))
```


```{r}
variable_tot <- rbind(
  response_summary_tot %>%
    mutate( Type = "Response") %>%
    select(Type, Variable = `Community metric`, everything()),
  evt_summary %>%
    mutate(Type = "Predictor") %>%
    select(Type, Variable = `Environmental variables`, everything())

) %>%
mutate(
  Variable = str_replace(Variable, "\n", ""),
  `(Min, Max)` = str_replace(`(Min, Max)`, " ", "")
)

variable_tot %>%
  kbl(booktabs = T,
    label = "tab-resp",
    caption = "Summary descriptors of response and environmental
      variables. Main text names display the name used in the legend of the
      figures in main text. The community metrics that do not have main text
      name were not used in the analysis reported in main text."
    ) %>%
  collapse_rows(columns = 1, latex_hline = "major", valign = "middle") %>%
  column_spec(column = 2, width="6cm") %>%
  kable_styling(latex_options = c("striped", "hold_position", "scale_down"))
```

```{r}
cap_pca_riv <- "Rotated PCA over the physical and hydrological structure of
streams. The first axis is related the average discharge, the Strahler order and the
distance from source. This first axis was used in the statistical modelling as a
composite variable to summarise the stream gradient from upstream to downstream."
```

```{r pca-riv-str, fig.cap=cap_pca_riv}
p_pca_riv_str <- plot_pca_clust(
  .data = pca_riv_str$rotated,
  site_cl = NULL,
  xaxis = "RC1", yaxis = "RC2",
  ctb_thld = .4, label_size = 2,
  size_abscisse_segment = .25,
  size_arrows_segment = .25,
  force = 10, force_pull = 1,
  var_scaling_factor = NULL,
  seed = NA,
  replace_var = get_rev_vec_name_val(get_river_atlas_significant_var()),
  add_variable = TRUE,
  add_point = FALSE,
  add_ellipse = FALSE
)
p_pca_riv_str
```

```{r}
lc_hft <- riveratlas_site %>%
  st_drop_geometry() %>%
  select(any_of(c(
        get_land_class_var()[str_detect(names(get_land_class_var()), "catchment")],
        get_river_atlas_significant_var()[
          str_detect(get_river_atlas_significant_var(), "hft_")
          ]
        )))
```

```{r}
cor_lc_hft <- cor(lc_hft,
  method = "spearman"
)
#corrplot::corrplot(cor_clust, type = "upper", diag = FALSE, tl.srt = 15)
p_cor_lc_hft <- ggcorrplot::ggcorrplot(
  cor_lc_hft, hc.order = TRUE, type = "lower",
  lab = TRUE, tl.srt = 15, legend.title = "Spearman Corr") +
theme(legend.position = c(.45, .95), legend.direction = "horizontal") +
guides(colour = guide_legend(title.position = "top"))
```

```{r cor-lc-hft, fig.width = 12, fig.cap="Spearman correlation between land uses and human footprint indexes"}
p_cor_lc_hft
```

\newpage

```{r, eval = FALSE}
variable_stat <- tibble(
  category = c(rep("Response variable", 10), rep("Predictor variable", 7)),
  variables = c(clust_var, "perc_exo_sp", "perc_exo_abun", "log1_year_nb",
    "riv_str_rc1", "hft_ix_c93", "hft_ix_c9309_log2_ratio", "unitabundance",
    "main_bas", "siteid"),
  names = c(get_model_term_replacement_paper_figure(),
    get_var_replacement_vulgarisation())[variables],
  var_type = c("Numeric", "Continuous", rep("Proportion", 8), "Continuous",
    "Continuous", "Continuous", "Proportion", "Factor", "Character",
    "Character"),
  unit = c("cf Abundance unit", rep("", 8), "",
  "Number of year", "", "", "", "Factor with 4 levels: Count (reference), Number of individuals by 100 sq meters,
    Catch per Unit Effort (CPUE), Leslie index", "", ""),

  signification = c(
    "Total number of individuals",
    "Coverage corrected richness",
    "Temporal dissimilarity
    (presence/absence)",
    "Temporal dissimilarity
    (relative abundance, Simpson index)",
    "Temporal species
    colonisation",
    "Temporal species
    exptirpation", "Temporal species
    replacement", "Temporal
    nestedness",
    "Proportion of
    non-native species richness",
    "Proportion of
    non-native species abundance", "Time",
    "PCA axis related to average flow,
    distance from source, Strahler order, stream size",
    "Human footprint (1993)",
    "Human footprint ratio
    between 2009 and 1993",
    "Unit of abundance", "Hydrographic basin", "Sampled site"
    ),
    transformation = c("Log", "Log", rep("", 8), "Log + 1", "", "",
      "Log base 2", "", "", "")
    ) %>%
mutate(across(everything(), ~str_remove_all(., "\n")))

variable_stat %>%
  select(-variables, `short name` = names, type = var_type) %>%
  rename_with(str_to_sentence) %>%
  kbl(booktabs = T,
    label = "tab-var-mod",
    caption = "Description of the variables included in the model.") %>%
  collapse_rows(columns = 1, latex_hline = "major", valign = "middle") %>%
  column_spec(4, width = "3cm") %>%
  column_spec(5, width = "3cm") %>%
  kable_styling(latex_options = c("striped", "hold_position"))
```


```{r}
vif_caption <- "Variance inflation factors on the variables included in the
model. SE factor: inflation of the standard error of slope coefficients
predicted by the multicollinearity of the variables. The VIF values were all
close to 1, indicating absence of multicollinearity."
```


```{r vif}
dummy_vif <- lm(log_species_nb ~
   log1_year_nb + riv_str_rc1 +
     hft_ix_c9309_log2_ratio +
    hft_ix_c93, modelling_data)
ck_col_data <- check_collinearity(dummy_vif) %>%
  as_tibble() %>%
  mutate(Term = str_replace(get_model_term_replacement()[Term], "\n", " ")) %>%
  rename(`SE factor` = "SE_factor", "Predictive variables" = "Term")
```

```{r}
ck_col_data %>%
  kbl(booktabs = T,
    label = "tab-vif",
    caption = vif_caption
    ) %>%
  kable_styling(latex_options = c("striped", "hold_position"))
```

```{r}
tar_load(c(dic_waic_comp_time, clust_var, exo_resp_var))
cap_aic_table <- "Watanabe-Akaike
information criterion (WAIC) of the statistical models fitting temporal trends with 
either the number of year since the start of sampling or the log of the former 
variable added to one." %>%
str_remove_all("\n")
```

```{r}
tar_load(tab_waic)
tab_waic %>%
  kbl(booktabs = T,
    label = "tab-aic",
    caption = cap_aic_table
    ) %>%
  column_spec(5, width = "4cm") %>%
  kable_styling(latex_options = c("striped", "hold_position")) %>%
  add_header_above(c(" " = 1, "WAIC" = 2, " " = 2))
```


```{r}
tar_load(c(obs_fit, r2_obs_fit))
tar_load(gaussian_inla_exo_std)
cpo <- gaussian_inla_exo_std %>%
  mutate(
    cpo_pit = map(mod, ~inla.cpo(.x)),
    cpo = map(cpo_pit, ~.x$cpo$cpo),
    pit = map(cpo_pit, ~.x$cpo$pit)
    ) %>%
  select(-mod)

r2_obs_fit <- obs_fit %>%
  filter(response %in% c(clust_var, exo_resp_var)) %>%
  mutate(response = get_var_replacement_vulgarisation()[response]) %>%
  group_by(response) %>%
  summarise(
    cor = round(cor(y = fit, x = obs), 2),
    r2 = round((cor(y = fit, x = obs))^2, 2),
    gelman_r2 = round(var(fit) / (var(fit) + var(obs - fit)), 2),
    lab_r2 = paste0("~~~~R^2 == ", gelman_r2),
    lab = paste0("\n~~~~rho == ", cor),
    obs = -Inf,#(max(obs) - min(obs)) * .10,
    fit = Inf#(max(fit) - min(fit)) * .90
  )
```

```{r}
obs_fit_cap <- "Fitted values by the models vs observed values. The black line
displays the bisection, i.e. the intercept and slope are respectively 0 and 1.
Sticks located at the abscissa and ordinate axis display value concentration.
The Pearson's correlation coefficient is displayed in each panel."
```


```{r fit-obs, fig.width = 10, fig.asp = 1, fig.cap = obs_fit_cap}
tar_load(p_obs_fit)
p_obs_fit
```





```{r}
tar_load(c(clust_curv_site, clust_curv_site_fac_50))
tar_load(c(k6_fac_1, sup_clust_size_fac1))
```

```{r}
cap_clust_curv <- "Objective function quantifying the goodness of k-means
clustering according the percentage of removed data (most outliers data in the
  multidimentional space) removed. In the results presented in the main text, we
removed 5% of the data. Left and right panels displayed results for restricting
factors of 1 and 50 respectively. Restricted factor of 1 was used for the main
text"
```

```{r, fig.show = "hide"}
library(tclust)
p1 <- ~{plot(clust_curv_site)}
p2 <- ~{plot(clust_curv_site_fac_50)}
p <- plot_grid(
  ggdraw(p1),
  ggdraw(p2),
  ncol = 2
)
```


```{r, fig.width = 12, fig.asp = .5, fig.cap=cap_clust_curv}
p
```

```{r}
k4_cap <- "Display of the sites in the multidimentional space, colored by their cluster belonging. Number of clusters = 4"
```


```{r k4, fig.cap = k4_cap, results = "hide"}
k4_fac_1_cl <- tclust(
  x = site_no_drivers_inla_tot[, clust_var] %>%
  mutate(across(everything(), ~scale(., center = FALSE)[,1])),
  iter.max = 150,
  k = 4,
  alpha = 0.05,
  restr.fact = 1,
  warnings = 2
)
```

```{r}
bp_cl_dist_cap <- "Distribution of scaled temporal trends by variable and
cluster, for four clusters. With four cluster instead of six in the main text,
the clustering groups temporal trends of species richness and of total
abundance and the cluster characterising low change (Fig. 2, main text) is not
present."
```


```{r bp-k4, fig.width = 10, fig.asp = .6, fig.cap=bp_cl_dist_cap}
site_k4_fac_1_cl <- get_cluster_df(
     tclust_obj = k4_fac_1_cl,
     site_env = site_env,
     assign_threshold = .5,
     clean_method = "rm"
     )
bp_cl4 <- target_bp_cl_dist(cl_obj = site_k4_fac_1_cl,
  fct_var_lvl = names(pal_variable)[1:8],
  dodge = .85) +
  theme(legend.position = "bottom") +
  guides(colour = "none")
bp_cl4
```



